### ISSUE TITLE
Delete temp production deploy from the prototype.

### ISSUE THREAD

**Issue by mattpen** [phetsims/circuit-construction-kit-ac#14]
Per request from @kathy-phet, there was a temporary dev version deployed to the production location.  This must be removed from phet-server before version 1.0 is deployed with the build server.

It can be removed by running the following on phet-server:

`rm -rf /data/web/static/phetsims/sims/html/circuit-construction-kit-ac`

Contact me if there are any questions.

**Comment by samreid** [comment]
On hold until we are ready to deploy a production version.

**Comment by samreid** [comment]
Removing hold to help me remember to do this before 1.0 publication.  Do we also need to do this for virtual lab?

**Comment by samreid** [comment]
@mattpen it's been a while since we wrote this issue.  Is it still up-to-date, complete and accurate?

**Comment by mattpen** [comment]
I think I just need to add that we should coordinate the timing with @oliver-phet as we'll want to remove the link published at https://phet.colorado.edu/en/simulations/prototypes. The rm statement is still accurate.

**Comment by samreid** [comment]
Thanks, I invited @oliver-phet to the issue and will ping him on slack.  We just have one issue left and a spot check RC, so this could be happening soon.

**Comment by arouinfar** [comment]
I can take care of removing the sim from the prototype page, so unassigning @oliver-phet.

**Comment by samreid** [comment]
It sounds to me like the prototype can be removed from the prototype page after publication, please correct me if that's wrong.

**Comment by mattpen** [comment]
> It sounds to me like the prototype can be removed from the prototype page after publication, please correct me if that's wrong.

It's ok with me, but @arouinfar or @oliver-phet may have opinions on that.

**Comment by oliver-phet** [comment]
> It sounds to me like the prototype can be removed from the prototype page after publication, please correct me if that's wrong.

Yes, it's fine to remove the prototype after publication. IMO, the timing of removing prototypes from the Google doc isn't critical since both the prototype and the final published version use the same URL. FYI - there are updates in the works to better support prototypes on the website (adding sim pages, inclusion in browse/filter) that will eliminate the need to "manage" prototypes.

**Comment by samreid** [comment]
Can I temporarily move `/data/web/static/phetsims/sims/html/circuit-construction-kit-ac` in case there is a build error and the prototype needs to be restored?  Also, are we worried about taking the prototype offline for N minutes while we do the build?

**Comment by mattpen** [comment]
A temporary move is fine, but the files are backed up in the  peta library as well. 

Minimizing the down time sounds ideal, the sim is setting 1-2k uses per day.

**Comment by samreid** [comment]
Hopefully publishing this today, @mattpen let me know if you want to tag along in case there is trouble.

**Comment by samreid** [comment]
@mattpen and I checked for a virtual lab prototype, but didn't see one.

**Comment by mattpen** [comment]
@samreid and I successfully deployed 1.0.0, which replaced the temporary prototype.  I think this issue can be closed.
