### ISSUE TITLE
Items in carousel are too close together

### ISSUE THREAD

**Issue by ghost** [phetsims/circuit-construction-kit-ac#16]
On my MacBook Air 13.3-inch (1440 x 900), the items in the carousel are a bit too close together.

![issue](https://user-images.githubusercontent.com/31285590/77204161-c2eb9580-6ab7-11ea-9989-c924111fce02.png)

Seen on macOS 10.15.2 + Chrome 80.0.3987.132.

**Comment by arouinfar** [comment]
Thanks @lmulhall-phet. This will be addressed in the pixel polishing for https://github.com/phetsims/circuit-construction-kit-common/issues/507.
