### ISSUE TITLE
Design Idea from MK: Have RMS value option for meters

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-ac#17]
MD has mentioned that it would be great to have an option on the voltage and current meters to have a switch labeled DC or AC. When in DC, it gives realtime voltage in AC it displays the RMS values of voltage and current. Or alternatively, make another tab where AC only, and use more real world AC values. At any rate, we should further discuss with Mike on feature ideas in this vein. 

Did I give this the right label?

**Comment by arouinfar** [comment]
I'm going move this over to https://github.com/phetsims/circuit-construction-kit-common/issues/578, which is also a user request for RMS.
